site_name: Padrão de documentação
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: "Trocar para modo claro"

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: "Trocar para modo escuro"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: "Trocar para preferências do sistema"
  language: pt
  favicon: img/hype_logo.png
  logo: img/hype_logo_escura.png

repo_name: "pyproject-template"
repo_url: "https://github.com/pcastr/pyproject-template"

# watch:
#   - src
#   - tests
#
plugins:
  - search
  - mkdocstrings: 
      default_handler: python

markdown_extensions:
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid


nav:
  - Home: index.md
  - Docs:
    - 'Premissas da documentação': premissas-doc.md
    - 'Padrões de documentação': patterns-doc.md

extra_css:
  - stylesheets/extra.css

