[tool.poetry]
name = "venv"
version = "0.0.1"
description = "Projeto template"
authors = ["pcastr"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"
taskipy = "^1.12.2"
pandas = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
